// <auto-generated />
using System;
using BackEndNovo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BackEndNovo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20181109212905_nova")]
    partial class nova
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BackEndNovo.Model.Pedido", b =>
                {
                    b.Property<long>("pedidoid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cidade");

                    b.Property<string>("cliente");

                    b.Property<DateTime>("data");

                    b.Property<string>("estado");

                    b.Property<double>("total");

                    b.HasKey("pedidoid");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("BackEndNovo.Model.PedidoProduto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("pedidoid");

                    b.Property<long>("produtoid");

                    b.HasKey("id");

                    b.HasIndex("pedidoid");

                    b.HasIndex("produtoid");

                    b.ToTable("PedidoProduto");
                });

            modelBuilder.Entity("BackEndNovo.Model.Produto", b =>
                {
                    b.Property<long>("produtoid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("categoria");

                    b.Property<string>("nome");

                    b.Property<double>("valor");

                    b.HasKey("produtoid");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("BackEndNovo.Model.PedidoProduto", b =>
                {
                    b.HasOne("BackEndNovo.Model.Pedido", "pedido")
                        .WithMany("PedidoProduto")
                        .HasForeignKey("pedidoid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BackEndNovo.Model.Produto", "produto")
                        .WithMany("PedidoProduto")
                        .HasForeignKey("produtoid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
